uitoolkit/xlib/ui_window.c

Incorrect number of elements of the _MOTIF_WM_HINTS property could be written. Must always be 5.

Fix for writing all five elements of "_MOTIF_WM_HINTS" property.

---

doc/en/README.fb
doc/ja/README.fb
uitoolkit/fb/ui_display_x68kgrf.c

Tested on X68030 running NetBSD/x68k 9.1.
https://twitter.com/tsutsuii/status/1325804754857988097
https://twitter.com/tsutsuii/status/1325830049539354626
https://twitter.com/tsutsuii/status/1326171737457795074

Add X68030 CRT Mode 19 (640x480x4) support for mlterm-x68kgrf.

---

man/mlterm.1

“bold read character” → “bold red characters”
[“read” is not a color and use plural of character]

fix mlterm(1) spelling mistake

---

uitoolkit/fb/ui.h
uitoolkit/fb/ui_color.c
uitoolkit/fb/ui_display_freebsd.c
uitoolkit/fb/ui_display_linux.c
uitoolkit/fb/ui_display_wscons.c
uitoolkit/fb/ui_imagelib.c

For NetBSD/aarch64eb and armeb, framebuffer seems byte-swapped to CPU,
which was initially configured to little-endian mode by firmware and
switched to big-endian mode by kernel. Therefore, ARGB8888 fb becomes
BGRA8888, for example.
For Linux and FreeBSD, use alpha offset set by fb drivers. I cannot
test them. Sorry.
For wscons on NetBSD, unfortunately, alpha offset and size are not
set by (most?) fb drivers (they are 0). Therefore, we need to guess
them from offsets and sizes of red, green, and blue.

Stop hardcode alpha offset to 24 for 32-bpp fb.

---

vtemu/vt_parser.c

Please see https://github.com/dankamongmen/notcurses/issues/1782 for background context. `DECSDM` in MLterm is reversed compared to most terminals I've tested with (e.g. Alacritty, Contour, Kitty, XTerm, and WezTerm).

[decsdm] scrolling/cursor-based-positioning when *sent*

---

uitoolkit/xlib/ui_imagelib.c

Hi Araki-san,
This image is screenshots for little-endian server and big-endian client, before and after applying this patch.
Before applying the patch, color pattern of sixel image seems byte-swapped. A similar failure occurs for
big-endian server and little-endian client. I've confirmed that both combinations are fixed.

Fix color of sixel image on X server whose byte-order is opposite to client.

---

uitoolkit/fb/ui_display_wscons.c

Requires amidisplaycc(4) driver from NetBSD-current. With older
drivers, automatically falls back to monochrome mode.
XXX
Only tested for 8-bpp mode. As 4-bpp mode requires ancient
analogue monitors.
XXX
Logic to detect planar fb is not very elegant...

Add support for 8- and 4-bpp planar fb found on NetBSD/amiga.

---

vtemu/vt_parser.c

IM should be turned off if Ps is omitted, see:
https://ttssh2.osdn.jp/manual/4/ja/about/ctrlseq.html

Fix TTIMEST (CSI < Ps t).

---

uitoolkit/ui_im.c
uitoolkit/ui_sb_view_factory.c

The buffer length for appending suffix to module name is not correctly calculated. Fix the calculation to avoid memory corruption.

Fix buffer overflow with long plugin suffix

---

uitoolkit/fb/ui_display_linux.c

The modifiers can be remapped in the kernel as well, read the keymap to resolve them.
Fixes: #60

fb: Linux: Use kernel keymap for modifiers

---

baselib/configure
baselib/configure.in
configure
configure.in

Clang 16 makes -Wimplicit-function-declaration and -Wimplicit-int errors by default.
Unfortunately, this can lead to misconfiguration or miscompilation of software as configure tests may then return the wrong result.
For more information, see LWN.net [0] or LLVM's Discourse [1], the Gentoo wiki [2], or the (new) c-std-porting mailing list [3].
[0] https://lwn.net/Articles/913505/
[1] https://discourse.llvm.org/t/configure-script-breakage-with-the-new-werror-implicit-function-declaration/65213
[2] https://wiki.gentoo.org/wiki/Modern_C_porting
[3] hosted at lists.linux.dev.

Fix configure.ac compatibility with Clang 16

---

man/mlterm.1
uitoolkit/ui_main_config.c
uitoolkit/ui_main_config.h
uitoolkit/ui_screen_manager.c
vtemu/mlterm.c
vtemu/vt_parser.c
vtemu/vt_parser.h
vtemu/vt_term.c
vtemu/vt_term.h
vtemu/vt_term_manager.c
vtemu/vt_term_manager.h

Hi,
Thank you for mlterm.
One feature I'm used to in other terminals is the ability to set the window title and then don't allow an OSC seq to change it.
Here is a hack attempt PR at that, where if the title is specified then it is locked.
Another way would be a specific, separate lock_title option.
What do you think ?
thx,
-m

Add new use_locked_title (bool) option (default==false) to lock mlterm window title

---

.github/workflows/ci.yml

This appeases annotations/warnings on Actions:
> build (macos-latest)
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> build (macos-latest)
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

* ci.yml: Use the latest github-action checkout.

---

tool/mlconfig/Makefile.in

This fixes a github workflow CI test for NetBSD:
https://github.com/tsutsui/mlterm/actions/runs/8394742659/job/22992531392#step:3:8619
```
../../libtool --mode=link gcc main.o mc_combo.o mc_char_encoding.o mc_im.o mc_tabsize.o mc_logsize.o  mc_font.o mc_color.o mc_radio.o mc_space.o mc_alpha.o mc_ctl.o  mc_sb_view.o mc_wall_pic.o mc_bgtype.o mc_io.o mc_io_pty.o mc_io_file.o  mc_pty.o mc_char_width.o mc_flags.o mc_auto_detect.o mc_ratio.o mc_wordsep.o  mc_unicode_areas.o mc_geometry.o mc_click.o mc_opentype.o  -I/usr/pkg/include/gtk-3.0 -I/usr/pkg/include/pango-1.0 -I/usr/pkg/include/cairo -I/usr/pkg/include/gdk-pixbuf-2.0 -I/usr/X11R7/include -I/usr/pkg/include -I/usr/X11R7/include/freetype2 -I/usr/pkg/include/harfbuzz -I/usr/pkg/include/dbus-1.0 -I/usr/pkg/lib/dbus-1.0/include …
```

* tool/mlconfig/Makefile.in: @X_LIBS@ should be used to link -lX11.

---

.github/workflows/ci.yml

Using https://github.com/vmactions/netbsd-vm with possible most options.
(cairo, canna, fribidi, gdk-pixbuf2, gtk3, fcitx, ibus m17nlib, harfbuzz, scim, uim, freewmm, Xft, sdl2, libssh, vte)

* ci.yml: Add a CI test for NetBSD/amd64 10.0.

---

.github/workflows/ci.yml

It looks `netbsd-vm` package alread install glib2 (probably from pkgsrc-2024Q1) and if we will use newer pkgsrc versions we need "update" option for `pkg_add(1)` commands.

ci.yml: Explicitly use 'pkg_add -u' for NetBSD to install packages.

---

.github/workflows/ci.yml

* `fail-fast: false` seems necessary to avoid abort on errors on other OSes
* `case "${{ matrix.os }}"` in shell to switch OSes is more maintainable

Fix CI matrix

---

uitoolkit/wayland/ui_display.c

Fixes the following warning:
```
../uitoolkit/wayland/ui_display.c: In function 'ui_display_open':
../uitoolkit/wayland/ui_display.c:2748:5: warning: implicit declaration of function 'ui_event_source_add_fd' [-Wimplicit-function-declaration]
2748 |     ui_event_source_add_fd(-10, auto_repeat);
|     ^~~~~~~~~~~~~~~~~~~~~~
```
Note this "implicit function declaration" warning is treated as a fatal error on archLinux with gcc14.

* wayland/ui_display.c: Fix implicit function decl.

---

.github/workflows/ci.yml

- use docker for Linux: ubuntu:latest (currently 24.04), ubuntu:22.04, debian:12, debian:11, and archlinux:base
- explicitly call `apt upgrade -y` as usual updates by users
- also add more input method (ibus, m17n-lib, wnn, and canna) to ubuntu (and debian)
- macos now has a separate entry

Use docker to Linux CI to test more distributions

---

.github/workflows/ci.yml

This should have been in https://github.com/arakiken/mlterm/commit/65787afaf1427f364fd3e14087188b9fe5c1ad02 and now configure probes fcitx5 properly:
```
Mlterm was configured as follows
Installation path prefix          : /usr/local
Build shared libraries            : yes
Build static libraries            : yes
GUI toolkit                       : xlib
BiDi rendering (Fribidi)          : yes
Indic rendering                   : yes
OpenType Layout                   : yes (harfbuzz)
External tools                    : mlclient mlconfig mlcc mlterm-menu mlimgloader registobmp mlfc
Image processing                  : yes
Built-in image library            : 
utmp support                      : 
Type engines                      : xcore xft cairo
DnD                               : yes
Input …
```

* ci.yml: archLinux also requires fcitx5-gtk for Fcitx5GClient.

---

.github/workflows/ci.yml

Two changes for NetBSD CI:
* netbsd-vm installed glib2 from pkgsrc (maybe 2024Q2) but sometimes pkgsrc doesn't handle its dependencies properly and could cause warnings on updating gdk_pixbuf2 etc.:
```
g_module_open() failed for /usr/pkg/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so: /usr/pkg/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so: Undefined PLT symbol "g_once_init_enter_pointer" (symnum = 27)
g_module_open() failed for /usr/pkg/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.so: /usr/pkg/lib/libgdk_pixbuf-2.0.so.0: Undefined PLT symbol "g_once_init_enter_pointer" (symnum = 268)
g_module_open() failed for /usr/pkg/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so: /usr/pkg/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so: Undefined PLT …
```

Fix ci netbsd

---

uitoolkit/wayland/rescanproto.sh

cgit.freedesktop.org was down from 2024/8/19 to 2024/8/22 (though currently seems back) so archLinux CI failed.
Anyway I guess gitlab is the primary repository for upstream developers so well-maintained.

* rescanproto.sh: use gitlab.freedesktop.org rather than cgit.freedesktop.org.

---

man/mlterm.1

For changes in fb99b47d116da0eec44ce289eda14f086d59be12
```
+       * fb/x_display.c, fb/x_virtual_kbd.c, fb/x_window.c, x_window_cairo.c,
+         x_window_xft.c, win32/x_window.c, win32/x_xic.c,
+         x_im_candidate_screen.c, x_im_status_screen.c, x_main_config.c,
+         x_main_config.h, x_sb_screen.c, x_screen.[ch], x_screen_manager.c,
+         x_scrollbar.c, x_window.h, xlib/x_window.c, xlib/x_xic.c:
+         "inner_border" option accepts [horizontal border],[vertical border].
```

* man/mlterm.1: Update descriptions of --border and --lborder options.
